trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CmdLine@2
  inputs:
    script: 'brew install swig'
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'macosx'
    configuration: 'Release'
    xcWorkspacePath: 'DunGen.xcodeproj'
    xcodeVersion: 10 # Options: 8, 9, 10, default, specifyPath
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Mac Build'
    publishLocation: 'Container'
