trigger:
- master


jobs:
# - job: macOS
#   pool:
#     vmImage: 'macos-latest'
#   steps:
#   - task: CmdLine@2
#     inputs:
#       script: 'brew update; brew install swig'
#   - task: Xcode@5
#     inputs:
#       actions: 'build'
#       scheme: ''
#       sdk: 'macosx'
#       configuration: 'Release'
#       xcWorkspacePath: 'DunGen.xcodeproj'
#       xcodeVersion: 10
#   - task: PublishBuildArtifacts@1
#     inputs:
#       PathtoPublish: '$(Build.ArtifactStagingDirectory)'
#       ArtifactName: 'Mac Build'
#       publishLocation: 'Container'

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: VSBuild@1
    inputs:
      solution: 'DunGen.sln'
      vsVersion: '15.0'
      configuration: 'Release'
      maximumCpuCount: true
  - task: PublishBuildArtifacts@1
    inputs:
      PathToPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'Windows Build'
      publishLocation: 'Container'
