trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'macosx'
    configuration: 'Release'
    xcWorkspacePath: '/DunGen.xcodeproj/project.xcworkspace'
    xcodeVersion: 10 # Options: 8, 9, 10, default, specifyPath
