name: dungen
version: 0.0.1e
summary: Dungeon Generator
description: something
confinement: devmode
base: core
grade: devel

parts:
  dungen:
    plugin: nil
    source: ../
    build-packages: 
    - cmake
    - xorg-dev
    - libc6-dev
    - libx11-dev
    - libglu1-mesa-dev
    - libglew1.5-dev
    - libgl1-mesa-glx
    - libgl1-mesa-dev
    stage-packages:
    - libgl1-mesa-glx
    - libglu1-mesa
    override-build: |
      cd build
      cmake -G "Unix Makefiles" ..
      make
      mv ./DunGen $SNAPCRAFT_PART_INSTALL/DunGen
      mv ./Resources $SNAPCRAFT_PART_INSTALL/Resources

apps:
  DunGen:
    command: DunGen