AddBanner("Choice Coming Up...", 72, {1.0, 1.0, 1.0, 1.0}, {0.2, 0.2, 0.2, 0.5}, 5)
sir("WaitForUI", 1)
push()

AddChoice("Option A")
AddChoice("Option B")
AddChoice("Option C")
AddChoice("Option D")
AddChoice("Option E")
AddChoice("Option F")
AddChoice("Option G")
AddChoice("Option H")
AddChoice("Option I")
AddChoice("Option J")
AddChoice("Option K")
AddChoice("Option L")
PresentChoiceSelection()
sir("WaitForUI", 1)
push()
ClearChoices()
