name: Build DunGen (all platforms)
on: [push]
jobs:
  build-mac:
    runs-on: macos-11
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          brew install meson
      - name: Build release version
        run: |
          buildscripts/releases/macOS.sh
      - name: Run unit tests
        run: |
          build/DunGen_dist/DunGen.app/Contents/MacOS/DunGen startup=_testing.UnitTest

  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install meson build-essential clang libx11-dev libxi-dev libxcursor-dev libgl-dev
      - name: Build release version
        run: |
          buildscripts/releases/linux.sh
      - name: Run unit tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            build/DunGen_dist/DunGen startup=_testing.UnitTest
